export const RESTORE_SESSION = 'RESTORE_SESSION'
export const RESTORE_SESSION_SUCCESS = 'RESTORE_SESSION_SUCCESS'
export const SIGNIN = 'SIGNIN'
export const SIGNIN_FAILED = 'SIGNIN_FAILED'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNUP = 'SIGNUP'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_DONE = 'LOGOUT_DONE'

export const LOAD_COUNTRIES_LIST = 'LOAD_COUNTRIES_LIST'
export const LOAD_COUNTRIES_LIST_FAILED = 'LOAD_COUNTRIES_LIST_FAILED'
export const LOAD_COUNTRIES_LIST_SUCCESS = 'LOAD_COUNTRIES_LIST_SUCCESS'

export const LOAD_FOOD_PREF_LIST = 'LOAD_FOOD_PREF_LIST'
export const LOAD_FOOD_PREF_LIST_FAILED = 'LOAD_FOOD_PREF_LIST_FAILED'
export const LOAD_FOOD_PREF_LIST_SUCCESS = 'LOAD_FOOD_PREF_LIST_SUCCESS'

export const LOAD_PROFILE = 'LOAD_PROFILE'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'

export const VALIDATE_JWT = 'VALIDATE_JWT'
export const VALIDATE_JWT_SUCCESS = 'VALIDATE_JWT_SUCCESS'
export const VALIDATE_JWT_FAILED = 'VALIDATE_JWT_FAILED'

export const INITIATE_GOOGLE_SIGNIN = 'INITIATE_GOOGLE_SIGNIN'
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS'
export const GOOGLE_SIGNIN_FAILED = 'GOOGLE_SIGNIN_FAILED'
